### ISSUE TITLE
Problem with Spread

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [dodger487/dplython#97]
I am trying to reshape this data, but I am getting this error
![screen shot 2018-11-20 at 11 47 06](https://user-images.githubusercontent.com/37449624/48761636-34e07e80-ecba-11e8-9bf9-1fadc8d449fd.png)
![screen shot 2018-11-20 at 11 47 19](https://user-images.githubusercontent.com/37449624/48761646-3ad65f80-ecba-11e8-9e05-df717ade4004.png)

**Comment by bleearmstrong** [comment]
This bug is fixed with #83 .

**Comment by Shelmith-Kariuki** [comment]
The issue still persists, even with the addition of "convert_type=False"
![screen shot 2018-11-21 at 09 13 13](https://user-images.githubusercontent.com/37449624/48822364-dffe4000-ed6d-11e8-918c-1b282b8a7678.png)

**Comment by bleearmstrong** [comment]
it's not the `convert_type` that fixes the bug, it's one of the earlier commits in that pr (this one: https://github.com/dodger487/dplython/pull/83/commits/ced25d778db9d2bb689c60bcccf03e4125775554)

**Comment by Shelmith-Kariuki** [comment]
Hi, so I see where the issue is:
if not all(new_spread_data.groupby([new_spread_data.index, key._name]).agg('
count').reset_index().value < 2):
if not all(new_spread_data.groupby([new_spread_data.index, key._name]).agg('
count').reset_index()[values._name] < 2):

It seems as though the commit was not pushed to master. Or maybe I am using
the wrong package version (0.0.7).

**Comment by Shelmith-Kariuki** [comment]
Hi,

Still waiting on response to this issue.

Kind regards,

Shelmith

**Comment by bleearmstrong** [comment]
You are correct, the pr hasn't been merged. There's not much I can do about that, only @dodger487 can merge it.

**Comment by Shelmith-Kariuki** [comment]
Hi.

Okay, thanks a lot for feedback. Let us wait and hear from  @dodger487
<https://github.com/dodger487> .

**Comment by Shelmith-Kariuki** [comment]
Hi @dodger487,

I wanted to follow up on this. Last year, the only issue was spread, seems now we have an issue with both gather and spread. 
![screen shot 2019-02-08 at 12 34 19](https://user-images.githubusercontent.com/37449624/52470076-3bd2ab00-2b9e-11e9-907b-ab1dfaaed39b.png)

**Comment by gtsherman** [comment]
I know this is an old issue, but I just hit both of the problems @Shelmith-Kariuki mentioned, so I thought I'd post my workarounds.

The `spread` issue can be worked around by using the `spread` function from [tidypython](https://pypi.org/project/tidypython/) instead of from dplython. They're designed to play nicely together, so I there's nothing else to do except import from there and use it as normal.

The `gather` issue is the result of outdated dplython pypi packages, which don't include `gather`. Installing from git should fix the `gather` issue:
```
pip install git+https://github.com/dodger487/dplython.git
```

It seems like dplython isn't being updated these days, but it would be really great if the `spread` function could be fixed! @dodger487
